#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 Ryuta Kawamoto ryu073000@i.softbank.jp
# SPDX-License-Identifier: BSD-3-Clause

import sys

##入力された文字列と数値をリストにする関数
def read_food_data():
    foodname = []
    kc = []

    for line in sys.stdin:
        ##strip()で文字列の先頭と末尾の空白文字を削除
        n = line.strip()
        ##line.strip()の結果が[""]の場合を無視
        if not n:
            continue
        ##split()で文字列をスペースやタブごとに分割する
        name,cal = n.split()
        ##foodname（文字列のリスト）とkc（浮動小数点のリスト）に分割した文字列を代入
        foodname.append(name)
        kc.append(float(cal))

    return foodname,kc

##カロリーの合計の計算をする関数
def total_calories(kc_list):
    return sum(kc_list)

##基準値を超えたら警告を出す関数
def limit_calories(total,limit=2200.0):




if __name__ == "__main__":
    names,calories = read_food_data()
    
    print("--食事記録--")
    for n,c in zip(names,calories):
        print(f"{n}:{c}")


