#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 Ryuta Kawamoto <ryu073000@i.softbank.jp>
# SPDX-License-Identifier: BSD-3-Clause

import sys
ans = 0
for line in sys.stdin:
    try:
        ans += int(line)
    except:
        ans += float(line)

print(ans)
